version: '3.8'

services:
  libreoffice-converter:
    build:
      context: .
      dockerfile: Dockerfile.libreoffice
    container_name: cpq-libreoffice-converter
    ports:
      - "3002:3000"
    volumes:
      - ./temp-files:/temp
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Alternative: Use OnlyOffice Document Server (more features)
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: cpq-onlyoffice
    environment:
      - JWT_ENABLED=false
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - DB_PWD=onlyoffice
    ports:
      - "3003:80"
    volumes:
      - ./onlyoffice-data:/var/www/onlyoffice/Data
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - onlyoffice

  postgres:
    image: postgres:13
    container_name: cpq-postgres
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_PASSWORD=onlyoffice
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - onlyoffice
